### ISSUE TITLE
remove arrow icon

### ISSUE THREAD

**Issue by iamir4g** [Skylled/expansion_tile_card#17]
hi this [expansion_tile_card](https://github.com/Skylled/expansion_tile_card) is very useful but I want to remove the arrow icon, and I want to use all space of the card. how to this?

**Comment by iamir4g** [comment]
i want to design a card like this :
![WhatsApp Image 2020-12-20 at 16 02 19 (1)](https://user-images.githubusercontent.com/10659860/102758068-67707000-4387-11eb-8f6b-18bdb0f75f48.jpeg)

**Comment by Skylled** [comment]
One option to fix your issue today would be to replace the trailing with another widget. Perhaps the `SizedBox` widget, set to have 0 width and 0 height, might be a good choice.

I'm definitely open to the idea of there being an option without an arrow. We would need to maintain the current behavior of the arrow defaulting to on.

Perhaps we could set it up so that the variable `trailing` defaults to `Icon(Icons.expand_more)`, instead of the current behavior where null is replaced with the arrow.
